CREATE DATABASE IF NOT EXISTS `tools_sharding` /*!40100 DEFAULT CHARACTER SET utf8 */ /*!80016 DEFAULT ENCRYPTION='N' */;
CREATE TABLE IF NOT EXISTS `tools_sharding`.`tools_sharding_config` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `sys_id` bigint DEFAULT '0' COMMENT '系统编号',
    `logic_db` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'ts_db' COMMENT '逻辑库',
    `logic_tab` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'ts_tab' COMMENT '逻辑表',
    `db_sharding_column` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'created_at' COMMENT '分库键',
    `db_sharding_algorithm_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'AUTO-EXPANSION' COMMENT '库分片算法名称',
    `db_sharding_algorithm_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'AUTO-EXPANSION' COMMENT '库分片算法类名',
    `db_sharding_algorithm_kvs` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '库分片算法键值对',
    `tab_sharding_column` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'created_at' COMMENT '分表键',
    `tab_sharding_algorithm_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'AUTO-EXPANSION' COMMENT '表分片算法名称',
    `tab_sharding_algorithm_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'AUTO-EXPANSION' COMMENT '表分片算法类名',
    `tab_sharding_algorithm_kvs` varchar(255) DEFAULT NULL COMMENT '表分片算法键值对',
    `primary_key` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'id' COMMENT '主键名',
    `primary_key_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'snowflake' COMMENT '主键生成方式',
    `auditor_names` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'sharding_key_none_auditor' COMMENT '审计算法名称',
    `auditor_allow_hint_disable` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'true' COMMENT '禁用强制分片',
    `actual_data_nodes` text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '实际数据节点',
    `status` tinyint DEFAULT '1' COMMENT '状态',
    `created_by` bigint DEFAULT NULL COMMENT '创建人编号',
    `creator` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '创建人名称',
    `updated_by` bigint DEFAULT NULL COMMENT '修改人编号',
    `updater` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '修改人名称',
    `del` tinyint(1) DEFAULT '0' COMMENT '删除标识',
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_sys_id_logic_db_logic_table` (`sys_id`,`logic_db`,`logic_tab`) USING BTREE COMMENT '防止重复',
    KEY `ix_status` (`status`),
    KEY `ix_del` (`del`),
    KEY `ix_created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
